# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow integrates njsscan with GitHub's Code Scanning feature
# nodejsscan is a static security code scanner that finds insecure code patterns in your Node.js applications

name: njsscan sarif

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  build:
    # định nghĩa môi trường mà job sẽ chạy
    # Remove folder node43 nếu folder đó đã tồn tại
    runs-on: self-hosted
    steps:
      - name: Check if folder source BE exists
        run: |
          if [ -d "node43_ci_cd" ];then
            echo "Skip"
          else
            echo "Clone source code"
            git clone https://github.com/DuyPhuongkhtn/node43_ci_cd.git
            cd node43_ci_cd
          fi
      - name: Clone source code from github
        run: |
          echo "Start"
          cd node43_ci_cd
          git pull https://github.com/DuyPhuongkhtn/node43_ci_cd.git
          echo "Done"
      - name: Build mysql
        run: |
          CONTAINER_NAME=${{secrets.CONTAINER_NAME_SQL}}
          echo "get container name mysql $CONTAINER_NAME"
          if [ "$(sudo docker ps -a -q -f name=^${CONTAINER_NAME}$)" ];then
              echo "Container $CONTAINER_NAME exists"
          else
              echo "Build container mysql"
              sudo docker run -d --name $CONTAINER_NAME -e MYSQL_ROOT_PASSWORD=123456 -p 3306:3306 mysql:latest
          fi
      - name: Build source BE
        run: |
          # stop và remove container đã tồn tại
          # remove image
          # build image mới
          # tạo container mới
          cd node43_ci_cd
          sudo docker build . -t node43
          sudo docker run -d -p 8080:8080 --name node43 node43

